services:
  db:
    image: postgres:15-alpine
    container_name: wife-happifier-db
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wife-happifier
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
